# Generated by Django 4.1.3 on 2022-12-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
    ]
