# Generated by Django 4.1.3 on 2022-12-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_room_categore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"default_related_name": "rooms"},
        ),
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(blank=True, to="rooms.amenity"),
        ),
    ]
