# Generated by Django 4.1.3 on 2022-12-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_alter_room_options_alter_room_amenities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="categore",
            new_name="category",
        ),
    ]
