# Generated by Django 4.1.3 on 2022-12-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_experience_categore_alter_perk_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="categore",
            new_name="category",
        ),
    ]
