# Generated by Django 4.1.3 on 2022-12-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_rename_categore_experience_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"default_related_name": "experiences"},
        ),
        migrations.AlterModelOptions(
            name="perk",
            options={"default_related_name": "perks"},
        ),
    ]
