# Generated by Django 4.1.3 on 2022-12-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0002_alter_wishlist_experiences_alter_wishlist_rooms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={"default_related_name": "wishlists"},
        ),
    ]
