# Generated by Django 4.1.3 on 2022-12-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="experience_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="guests",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
